pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building in gatling..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing in gatling..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying in gatling....'
            }
        }
    }
}